---
title: "Presentations"
---

Espinosa, A.; Bargsted, M.; and Ortiz, F. (July, 2020). “Homofília en las Redes Personales: Estudio Longitudinal y Relacional”. Virtual Conference: Seminario ELSOC Cambio Social en Chile: Una perspectiva longitudinal. Centre for Social Conflict and Cohesion Studies (COES), Chile

Espinosa, A. (July, 2020). “Multilevel Mechanisms for the Study of Scientific Networks:  Mesolevel social forces in a (not so small) network for the stability of a national scientific field” Virtual Conference: XL Sunbelt Conference, International Network of Social Network Analysis (INSNA), National Centre for Scientific Research (CNRS); Sciences Po Paris, Paris, France.

Espinosa, A. (July, 2020). “Co-evolución de una red científica: análisis multinivel de una disciplina a nivel nacional” Virtual Conference: Red Hispano-americana – REDIris – Revista REDES

Espinosa, A. (September, 2019). “Micro-explanations for multilevel scientific networks: A stochastic actor-oriented model in a scientific discipline” Conference: 4th European Conference on Social Networks (EUSN 2019). Zürich, Switzerland.

Espinosa, A. (July, 2019). “Micro-explanations for multilevel scientific networks: A stochastic actor-oriented model in a scientific discipline” Conference: 5th International Conference on Computational Social Science (IC2S2 2019). Amsterdam, The Netherlands.

Espinosa, A. (June, 2019). “Co-evolution of a multilevel network in a national scientific discipline: A Stochastic Actor-Oriented Models for the study of scientific networks” Conference: XXXIX Sunbelt Conference, International Network of Social Network Analysis (INSNA), Université du Québec à Montréal, Montreal, Canada.

Espinosa, A. (April, 2019). “A Multilevel Dynamic Approach in Scientific Networks” Conference: British Sociological Association Annual Conference 2019 (BSA), Glasgow Caledonian University, UK.

Espinosa, A. (January, 2019). “Co-evolution of a multilevel network in a national scientific discipline: exploration of tripartite and multilevel mechanisms using stochastic actor-oriented models”. Labsgroups Seminars, Center for Research in Social Complexity (CICS), Universidad del Desarrollo, Chile.

Espinosa, A. (December, 2018). “Dynamic networks in a national discipline: using Stochastic Actor-Oriented Models for the study of scientific networks”. X Chilean Congress of Sociology, Workshop: ‘Methodology and Epistemology in the Social Science’, Iquique, Chile.

Espinosa, A. (December, 2018). “Personal networks and scientific recognition: relational strategies in a scientific community”. X Chilean Congress of Sociology, Workshop: ‘Sociology of Science, Technology and Innovation’, Iquique, Chile.

Espinosa, A. (October, 2018). “Scientifics Networks in a National Discipline: A Multilevel Dynamic Network Approach.” The Social Networks Labs.’ Seminars, the Eidgenössische Technische Hochschule (ETH), Zürich, Switzerland

Espinosa, A. (October, 2018). “A multilevel approach in the social network analysis: How micro-mechanisms can represent complex structures in dynamic scientific networks”. Sociology PGR Colloquium, the University of Manchester, Manchester, U.K.

Espinosa, A. (June, 2018). “Scientific collaboration in a national discipline: Co-evolution of one-mode and bipartite networks”. XXXVIII Sunbelt Conference, International Network of Social Network Analysis (INSNA), the University of Utrecht, Utrecht, The Netherlands. 

Espinosa, A. (June, 2018). “Scientific networks in the south of the world”. The Place I Call Research: Localizing Sociological Inquiry, the University of Manchester, Manchester, U.K.

Espinosa, A. (February, 2018). “Scientific collaboration in a national discipline: Co-evolution of one-mode and bipartite networks”. Thinking Chile, the University of Edinburgh, U.K.

Espinosa, A. (May, 2017). “Prospection of the Astroinformatics Field for the Next Decade”. Workshop of SoCVis, Department of Engineering and Computer Sciences, Pontifical Catholic University of Chile, Santiago, Chile.

Espinosa, A. (April, 2017). “Interlocking Networks of Corporate Directorships: Detection of Communities and Inferential Models for the characterization of Corporate Relationships”. Workshop, Faculty of Economy and Management, Desarrollo University, Santiago, Chile.

Espinosa, A. (January, 2017). “Managing Complexity in the Chaos of Science: Social Network Analysis for the Medicine Based in ‘Evidence’”. IV Meeting of the Chilean Network of Science, Technology and Society, Workshop: ‘Science and Scientometrics’, Valdivia, Chile.


Espinosa, A. (October, 2016). “Groups of Influence in Chilean Inter-locking Networks: Community Detections and Exponential Random Graph Models”. IX Chilean Congress of Sociology, Workshop: ‘Sociology of Economy’, Talca, Chile. 

Espinosa, A. (October, 2016). “The Production and Collaboration in the Scientific Recognition of Astronomy in Chile: Longitudinal Network Study of the Scientific Community, 1988-2013”. IX Chilean Congress of Sociology, Workshop: ‘Sociology of Science, Technology and Innovation’, Talca, Chile.

Espinosa, A. (October, 2014). “Social Stratification in Chilean Astronomy: Matthew Effect in ISI-Paper Networks”. VIII Chilean Congress of Sociology, Workshop: ‘Sociology of Science, Technology and Innovation’, La Serena, Chile.

Espinosa, A. (January, 2014). “Allocation of Scientists in the Atacama Large Millimeter/Submillimeter Array Astronomical Observatory”. First Meeting of the Chilean Network of Science, Technology and Society, Workshop: ‘Productivity and Appropriation of Science and Technology’, Santiago, Chile.

Espinosa, A. (October, 2013). “Technical Performativity in Outdoor Team Training: Ethnographic Notes in Experience Center “Nuevos Vientos””. XXIX Latin American Congress of Sociology, Workshop: ‘Science and Technology’, Santiago, Chile.

Espinosa, A. and Ortiz, F (September, 2013). “Private Jurisdictional Legitimation in the Transnational Regulatory Regime of FIFA”. XXIX Latin American Congress of Sociology, Workshop: ‘Sport, Leisure and Free Time’, Santiago, Chile.

Espinosa, A. (October, 2012). “Inclusion and Exclusion in an Art Museum”. VII Chilean Congress of Sociology, Workshop: ‘Sociology of Art and Heritage Studies’, Pucón, Chile.

Espinosa, A. (June, 2012). “Latin American Social Movement in the Horizon of World Society”. XXI Chilean Student Congress of Sociology, Workshop: ‘Social Movements, Politics and Citizen Participation in Latin America”, Valparaíso, Chile.

Espinosa, A.; Moyano, C. and Ortiz, F. (May, 2012). “Exclusion and Inclusion in a Museum of Contemporary Art: Cultural Foundation Plaza Mulato Gil de Castro”. Seminar “Young Researchers”, Santiago, Chile.

