---
title: "Research"
---

My dissertation research, under the supervision of [Dr Elisa Bellotti](https://www.research.manchester.ac.uk/portal/elisa.bellotti.html), [Prof Martin Everett](https://www.research.manchester.ac.uk/portal/martin.everett.html) and [Dr Termeh Shafie](https://www.research.manchester.ac.uk/portal/termeh.shafie.html) at [The Mitchell Centre for Social Network Analysis](https://www.socialsciences.manchester.ac.uk/mitchell-centre/), the University of Manchester focused on the sociological study of scientific networks from a multilevel perspective. The first part of my research is a theoretical analysis of the dilemma between "groups" and "communities" in the sociogenesis of the social network perspective, and the network approach to study scientific networks. Next, I apply this perspective into three empirical applications. The first part starts from a macro perspective distinguishing between different citation-based measures to study scientific networks. Then, I compare parallel networks of a scientific community to identify the common meso-level forces. Finally, I analyse a tripartite multilevel network in which I expand different goodness of fit for the analysis of the interdependency among co-evolving networks.

# *Last publications*

- Le Foulon, Carmen; Valenzuela, Paulina; Alenda, Sthepanie & **Espinosa, Alejandro** (2020). “Methodology of the survey applied to the leaders of the political coalition Chile Vamos”. In: Alenda, Stephanie (ed.), Anatomía de la derecha chilena: Estado, mercado y valores en tiempos de cambios. Fondo de Cultura Económica, 347-357 
- **Espinosa-Rada, Alejandro**; Ortiz, Francisca & Cereceda, Trinidad (2019). “Astroinformatics and the prospection of the astronomy in Chile: A sub-discipline in the global scenario, and a local scientific development”.  CUHSO · Cultura - Hombre - Sociedad. 29(2), 1-30. DOI: 10.7770/0719-2789.2019.CUHSO.0.0A00  
- **Espinosa-Rada, Alejandro**; Ortiz, Francisca & Sanhueza, Nicolás (eds.) (2018). Technopolitics: Approaches to the Study of Science, Technology and Society in Chile. Sociology Series: Alberto Hurtado University Press.
- Gonzalvez, Herminia; Ortiz, Francisca & **Espinosa, Alejandro** (2018). “Kinship networks of families from Santiago of Chile”. REDES-Revista Hispana para el Análisis de Redes Sociales, 27(1), 111-124. 
- **Espinosa, Alejandro** & Ortiz, Francisca (2016). “Jurisdictional autonomy in the regulatory transnational regime of FIFA”. REDES-Revista Hispana para el Análisis de Redes Sociales, 27(1), 100-112.  



